// Example samples
// ideally, samples should be < 1 minute or less

// Natural sounds
~rain = "sounds/rain.wav";
~fire = "sounds/fire.wav";
~stream = "sounds/stream.wav";

// Instruments
~piano = "sounds/piano.wav";
~violin = "sounds/violin.wav";

// Manmade noises
~machine = "sounds/machinery.wav";
~talking = "sounds/talking.wav";
~laugh = "sounds/talking.wav";

// Songs
~edm = "sounds/edm_sample.wav";
~pop = "sounds/pop_sample.wav";
